from flask_api import FlaskAPI, status
import requests
import json

app = FlaskAPI(__name__)
apiKey = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjJmNDI5MjNiLWRiNTMtNGRlZS1hN2Y4LTlkZGI5NzZkZTBmOCIsImlhdCI6MTUzNDM5NzA5MSwic3ViIjoiZGV2ZWxvcGVyLzMxNmM2ZGNiLTY2ZjQtNmNjMi0yZGU2LWY5ODVmMzRlYmNjYiIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyIxOTAuMTguMTkyLjE2NCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.uuMi19OF86eflvHCuDWft6WPFP0v0ViKO3HTdxyBwBn4_gjMbx_RuTYabJpTkXT0FVx_0huc1HY6O6X5M8eRxQ'

@app.route("/userTag/<string:tag>", methods=['GET'])
def playerData(tag):
	url = 'https://api.clashroyale.com/v1/players/%23' + str(tag)
	headers = {"Accept":"application/json" , "Authorization":"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjJmNDI5MjNiLWRiNTMtNGRlZS1hN2Y4LTlkZGI5NzZkZTBmOCIsImlhdCI6MTUzNDM5NzA5MSwic3ViIjoiZGV2ZWxvcGVyLzMxNmM2ZGNiLTY2ZjQtNmNjMi0yZGU2LWY5ODVmMzRlYmNjYiIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyIxOTAuMTguMTkyLjE2NCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.uuMi19OF86eflvHCuDWft6WPFP0v0ViKO3HTdxyBwBn4_gjMbx_RuTYabJpTkXT0FVx_0huc1HY6O6X5M8eRxQ"}
	response = requests.get(url=url, headers=headers)
	print(response)
	return response.json()

if __name__ == "__main__":
    app.run(debug=True)
